name: Deploy Frontend

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend via SSH

        uses: appleboy/ssh-action@4e3535e14ec03f79243a1a56045526c18d66d556
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            echo "🚀 Deploying Frontend..."
            
            # 1. Go to frontend folder
            cd ~/Bubble-Brain
            
            # 2. Get latest code
            git fetch --all
            git reset --hard origin/main
            
            # 3. Install & Build
            npm install
            npm run build
            
            # 4. Reload Nginx
            sudo systemctl reload nginx
            
            echo "✅ Frontend Deployed Successfully!"
